apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jarvis.fullname" . }}-postgres-migrations
  labels:
    {{- include "jarvis.labels" . | nindent 4 }}
data:
  001_platform_hub.sql: |-
{{ .Files.Get "files/postgres/migrations/001_platform_hub.sql" | indent 4 }}
